# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logiflow/dispatch/v1/dispatch.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'logiflow/dispatch/v1/dispatch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#logiflow/dispatch/v1/dispatch.proto\x12\x14logiflow.dispatch.v1\")\n\x10RecommendRequest\x12\x15\n\rsnapshot_json\x18\x01 \x01(\x0c\"1\n\x11RecommendResponse\x12\x1c\n\x14recommendations_json\x18\x01 \x01(\x0c\x32w\n\x17\x44ispatchRecommendations\x12\\\n\tRecommend\x12&.logiflow.dispatch.v1.RecommendRequest\x1a\'.logiflow.dispatch.v1.RecommendResponseB<Z:github.com/anxi0uz/logiflow/internal/dispatchpb;dispatchpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logiflow.dispatch.v1.dispatch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/anxi0uz/logiflow/internal/dispatchpb;dispatchpb'
  _globals['_RECOMMENDREQUEST']._serialized_start=61
  _globals['_RECOMMENDREQUEST']._serialized_end=102
  _globals['_RECOMMENDRESPONSE']._serialized_start=104
  _globals['_RECOMMENDRESPONSE']._serialized_end=153
  _globals['_DISPATCHRECOMMENDATIONS']._serialized_start=155
  _globals['_DISPATCHRECOMMENDATIONS']._serialized_end=274
# @@protoc_insertion_point(module_scope)
