# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from logiflow.dispatch.v1 import dispatch_pb2 as logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logiflow/dispatch/v1/dispatch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatchRecommendationsStub:
    """Synchronous recalculation uses the same versioned JSON snapshot/result as NATS.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommend = channel.unary_unary(
                '/logiflow.dispatch.v1.DispatchRecommendations/Recommend',
                request_serializer=logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2.RecommendRequest.SerializeToString,
                response_deserializer=logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2.RecommendResponse.FromString,
                _registered_method=True)


class DispatchRecommendationsServicer:
    """Synchronous recalculation uses the same versioned JSON snapshot/result as NATS.
    """

    def Recommend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchRecommendationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2.RecommendRequest.FromString,
                    response_serializer=logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2.RecommendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logiflow.dispatch.v1.DispatchRecommendations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logiflow.dispatch.v1.DispatchRecommendations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatchRecommendations:
    """Synchronous recalculation uses the same versioned JSON snapshot/result as NATS.
    """

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logiflow.dispatch.v1.DispatchRecommendations/Recommend',
            logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2.RecommendRequest.SerializeToString,
            logiflow_dot_dispatch_dot_v1_dot_dispatch__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
