# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logiflow/documents/v1/documents.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'logiflow/documents/v1/documents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%logiflow/documents/v1/documents.proto\x12\x15logiflow.documents.v1\"F\n\x14ListDocumentsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03 \x01(\r\"m\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nsize_bytes\x18\x06 \x01(\x04\"K\n\x15ListDocumentsResponse\x12\x32\n\tdocuments\x18\x01 \x03(\x0b\x32\x1f.logiflow.documents.v1.Document\"?\n\x17\x44ownloadDocumentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\"\x1d\n\rDocumentChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xe7\x01\n\rDocumentInbox\x12j\n\rListDocuments\x12+.logiflow.documents.v1.ListDocumentsRequest\x1a,.logiflow.documents.v1.ListDocumentsResponse\x12j\n\x10\x44ownloadDocument\x12..logiflow.documents.v1.DownloadDocumentRequest\x1a$.logiflow.documents.v1.DocumentChunk0\x01\x42<Z:github.com/anxi0uz/logiflow/internal/documentpb;documentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logiflow.documents.v1.documents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/anxi0uz/logiflow/internal/documentpb;documentpb'
  _globals['_LISTDOCUMENTSREQUEST']._serialized_start=64
  _globals['_LISTDOCUMENTSREQUEST']._serialized_end=134
  _globals['_DOCUMENT']._serialized_start=136
  _globals['_DOCUMENT']._serialized_end=245
  _globals['_LISTDOCUMENTSRESPONSE']._serialized_start=247
  _globals['_LISTDOCUMENTSRESPONSE']._serialized_end=322
  _globals['_DOWNLOADDOCUMENTREQUEST']._serialized_start=324
  _globals['_DOWNLOADDOCUMENTREQUEST']._serialized_end=387
  _globals['_DOCUMENTCHUNK']._serialized_start=389
  _globals['_DOCUMENTCHUNK']._serialized_end=418
  _globals['_DOCUMENTINBOX']._serialized_start=421
  _globals['_DOCUMENTINBOX']._serialized_end=652
# @@protoc_insertion_point(module_scope)
