# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from logiflow.documents.v1 import documents_pb2 as logiflow_dot_documents_dot_v1_dot_documents__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logiflow/documents/v1/documents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentInboxStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDocuments = channel.unary_unary(
                '/logiflow.documents.v1.DocumentInbox/ListDocuments',
                request_serializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.DownloadDocument = channel.unary_stream(
                '/logiflow.documents.v1.DocumentInbox/DownloadDocument',
                request_serializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.DownloadDocumentRequest.SerializeToString,
                response_deserializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.DocumentChunk.FromString,
                _registered_method=True)


class DocumentInboxServicer:
    """Missing associated documentation comment in .proto file."""

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentInboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.ListDocumentsRequest.FromString,
                    response_serializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'DownloadDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadDocument,
                    request_deserializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.DownloadDocumentRequest.FromString,
                    response_serializer=logiflow_dot_documents_dot_v1_dot_documents__pb2.DocumentChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logiflow.documents.v1.DocumentInbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logiflow.documents.v1.DocumentInbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentInbox:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logiflow.documents.v1.DocumentInbox/ListDocuments',
            logiflow_dot_documents_dot_v1_dot_documents__pb2.ListDocumentsRequest.SerializeToString,
            logiflow_dot_documents_dot_v1_dot_documents__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/logiflow.documents.v1.DocumentInbox/DownloadDocument',
            logiflow_dot_documents_dot_v1_dot_documents__pb2.DownloadDocumentRequest.SerializeToString,
            logiflow_dot_documents_dot_v1_dot_documents__pb2.DocumentChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
