// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: logiflow/dispatch/v1/dispatch.proto

package dispatchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DispatchRecommendations_Recommend_FullMethodName = "/logiflow.dispatch.v1.DispatchRecommendations/Recommend"
)

// DispatchRecommendationsClient is the client API for DispatchRecommendations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Synchronous recalculation uses the same versioned JSON snapshot/result as NATS.
type DispatchRecommendationsClient interface {
	Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
}

type dispatchRecommendationsClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchRecommendationsClient(cc grpc.ClientConnInterface) DispatchRecommendationsClient {
	return &dispatchRecommendationsClient{cc}
}

func (c *dispatchRecommendationsClient) Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, DispatchRecommendations_Recommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchRecommendationsServer is the server API for DispatchRecommendations service.
// All implementations must embed UnimplementedDispatchRecommendationsServer
// for forward compatibility.
//
// Synchronous recalculation uses the same versioned JSON snapshot/result as NATS.
type DispatchRecommendationsServer interface {
	Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error)
	mustEmbedUnimplementedDispatchRecommendationsServer()
}

// UnimplementedDispatchRecommendationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchRecommendationsServer struct{}

func (UnimplementedDispatchRecommendationsServer) Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recommend not implemented")
}
func (UnimplementedDispatchRecommendationsServer) mustEmbedUnimplementedDispatchRecommendationsServer() {
}
func (UnimplementedDispatchRecommendationsServer) testEmbeddedByValue() {}

// UnsafeDispatchRecommendationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchRecommendationsServer will
// result in compilation errors.
type UnsafeDispatchRecommendationsServer interface {
	mustEmbedUnimplementedDispatchRecommendationsServer()
}

func RegisterDispatchRecommendationsServer(s grpc.ServiceRegistrar, srv DispatchRecommendationsServer) {
	// If the following call pancis, it indicates UnimplementedDispatchRecommendationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DispatchRecommendations_ServiceDesc, srv)
}

func _DispatchRecommendations_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchRecommendationsServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchRecommendations_Recommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchRecommendationsServer).Recommend(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchRecommendations_ServiceDesc is the grpc.ServiceDesc for DispatchRecommendations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchRecommendations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logiflow.dispatch.v1.DispatchRecommendations",
	HandlerType: (*DispatchRecommendationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recommend",
			Handler:    _DispatchRecommendations_Recommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logiflow/dispatch/v1/dispatch.proto",
}
