// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: logiflow/dispatch/v1/dispatch.proto

package dispatchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotJson  []byte                 `protobuf:"bytes,1,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_logiflow_dispatch_v1_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_dispatch_v1_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_logiflow_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetSnapshotJson() []byte {
	if x != nil {
		return x.SnapshotJson
	}
	return nil
}

type RecommendResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RecommendationsJson []byte                 `protobuf:"bytes,1,opt,name=recommendations_json,json=recommendationsJson,proto3" json:"recommendations_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_logiflow_dispatch_v1_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_dispatch_v1_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_logiflow_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetRecommendationsJson() []byte {
	if x != nil {
		return x.RecommendationsJson
	}
	return nil
}

var File_logiflow_dispatch_v1_dispatch_proto protoreflect.FileDescriptor

const file_logiflow_dispatch_v1_dispatch_proto_rawDesc = "" +
	"\n" +
	"#logiflow/dispatch/v1/dispatch.proto\x12\x14logiflow.dispatch.v1\"7\n" +
	"\x10RecommendRequest\x12#\n" +
	"\rsnapshot_json\x18\x01 \x01(\fR\fsnapshotJson\"F\n" +
	"\x11RecommendResponse\x121\n" +
	"\x14recommendations_json\x18\x01 \x01(\fR\x13recommendationsJson2w\n" +
	"\x17DispatchRecommendations\x12\\\n" +
	"\tRecommend\x12&.logiflow.dispatch.v1.RecommendRequest\x1a'.logiflow.dispatch.v1.RecommendResponseB<Z:github.com/anxi0uz/logiflow/internal/dispatchpb;dispatchpbb\x06proto3"

var (
	file_logiflow_dispatch_v1_dispatch_proto_rawDescOnce sync.Once
	file_logiflow_dispatch_v1_dispatch_proto_rawDescData []byte
)

func file_logiflow_dispatch_v1_dispatch_proto_rawDescGZIP() []byte {
	file_logiflow_dispatch_v1_dispatch_proto_rawDescOnce.Do(func() {
		file_logiflow_dispatch_v1_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logiflow_dispatch_v1_dispatch_proto_rawDesc), len(file_logiflow_dispatch_v1_dispatch_proto_rawDesc)))
	})
	return file_logiflow_dispatch_v1_dispatch_proto_rawDescData
}

var file_logiflow_dispatch_v1_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logiflow_dispatch_v1_dispatch_proto_goTypes = []any{
	(*RecommendRequest)(nil),  // 0: logiflow.dispatch.v1.RecommendRequest
	(*RecommendResponse)(nil), // 1: logiflow.dispatch.v1.RecommendResponse
}
var file_logiflow_dispatch_v1_dispatch_proto_depIdxs = []int32{
	0, // 0: logiflow.dispatch.v1.DispatchRecommendations.Recommend:input_type -> logiflow.dispatch.v1.RecommendRequest
	1, // 1: logiflow.dispatch.v1.DispatchRecommendations.Recommend:output_type -> logiflow.dispatch.v1.RecommendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logiflow_dispatch_v1_dispatch_proto_init() }
func file_logiflow_dispatch_v1_dispatch_proto_init() {
	if File_logiflow_dispatch_v1_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logiflow_dispatch_v1_dispatch_proto_rawDesc), len(file_logiflow_dispatch_v1_dispatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logiflow_dispatch_v1_dispatch_proto_goTypes,
		DependencyIndexes: file_logiflow_dispatch_v1_dispatch_proto_depIdxs,
		MessageInfos:      file_logiflow_dispatch_v1_dispatch_proto_msgTypes,
	}.Build()
	File_logiflow_dispatch_v1_dispatch_proto = out.File
	file_logiflow_dispatch_v1_dispatch_proto_goTypes = nil
	file_logiflow_dispatch_v1_dispatch_proto_depIdxs = nil
}
