// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: logiflow/documents/v1/documents.proto

package documentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_logiflow_documents_v1_documents_proto_rawDescGZIP(), []int{0}
}

func (x *ListDocumentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListDocumentsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDocumentsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_logiflow_documents_v1_documents_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Document) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Document) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_logiflow_documents_v1_documents_proto_rawDescGZIP(), []int{2}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type DownloadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentRequest) Reset() {
	*x = DownloadDocumentRequest{}
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentRequest) ProtoMessage() {}

func (x *DownloadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentRequest.ProtoReflect.Descriptor instead.
func (*DownloadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_logiflow_documents_v1_documents_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DownloadDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type DocumentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_logiflow_documents_v1_documents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_logiflow_documents_v1_documents_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_logiflow_documents_v1_documents_proto protoreflect.FileDescriptor

const file_logiflow_documents_v1_documents_proto_rawDesc = "" +
	"\n" +
	"%logiflow/documents/v1/documents.proto\x12\x15logiflow.documents.v1\"]\n" +
	"\x14ListDocumentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\x9d\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x04R\tsizeBytes\"V\n" +
	"\x15ListDocumentsResponse\x12=\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1f.logiflow.documents.v1.DocumentR\tdocuments\"S\n" +
	"\x17DownloadDocumentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"#\n" +
	"\rDocumentChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xe7\x01\n" +
	"\rDocumentInbox\x12j\n" +
	"\rListDocuments\x12+.logiflow.documents.v1.ListDocumentsRequest\x1a,.logiflow.documents.v1.ListDocumentsResponse\x12j\n" +
	"\x10DownloadDocument\x12..logiflow.documents.v1.DownloadDocumentRequest\x1a$.logiflow.documents.v1.DocumentChunk0\x01B<Z:github.com/anxi0uz/logiflow/internal/documentpb;documentpbb\x06proto3"

var (
	file_logiflow_documents_v1_documents_proto_rawDescOnce sync.Once
	file_logiflow_documents_v1_documents_proto_rawDescData []byte
)

func file_logiflow_documents_v1_documents_proto_rawDescGZIP() []byte {
	file_logiflow_documents_v1_documents_proto_rawDescOnce.Do(func() {
		file_logiflow_documents_v1_documents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logiflow_documents_v1_documents_proto_rawDesc), len(file_logiflow_documents_v1_documents_proto_rawDesc)))
	})
	return file_logiflow_documents_v1_documents_proto_rawDescData
}

var file_logiflow_documents_v1_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_logiflow_documents_v1_documents_proto_goTypes = []any{
	(*ListDocumentsRequest)(nil),    // 0: logiflow.documents.v1.ListDocumentsRequest
	(*Document)(nil),                // 1: logiflow.documents.v1.Document
	(*ListDocumentsResponse)(nil),   // 2: logiflow.documents.v1.ListDocumentsResponse
	(*DownloadDocumentRequest)(nil), // 3: logiflow.documents.v1.DownloadDocumentRequest
	(*DocumentChunk)(nil),           // 4: logiflow.documents.v1.DocumentChunk
}
var file_logiflow_documents_v1_documents_proto_depIdxs = []int32{
	1, // 0: logiflow.documents.v1.ListDocumentsResponse.documents:type_name -> logiflow.documents.v1.Document
	0, // 1: logiflow.documents.v1.DocumentInbox.ListDocuments:input_type -> logiflow.documents.v1.ListDocumentsRequest
	3, // 2: logiflow.documents.v1.DocumentInbox.DownloadDocument:input_type -> logiflow.documents.v1.DownloadDocumentRequest
	2, // 3: logiflow.documents.v1.DocumentInbox.ListDocuments:output_type -> logiflow.documents.v1.ListDocumentsResponse
	4, // 4: logiflow.documents.v1.DocumentInbox.DownloadDocument:output_type -> logiflow.documents.v1.DocumentChunk
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logiflow_documents_v1_documents_proto_init() }
func file_logiflow_documents_v1_documents_proto_init() {
	if File_logiflow_documents_v1_documents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logiflow_documents_v1_documents_proto_rawDesc), len(file_logiflow_documents_v1_documents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logiflow_documents_v1_documents_proto_goTypes,
		DependencyIndexes: file_logiflow_documents_v1_documents_proto_depIdxs,
		MessageInfos:      file_logiflow_documents_v1_documents_proto_msgTypes,
	}.Build()
	File_logiflow_documents_v1_documents_proto = out.File
	file_logiflow_documents_v1_documents_proto_goTypes = nil
	file_logiflow_documents_v1_documents_proto_depIdxs = nil
}
