// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: logiflow/documents/v1/documents.proto

package documentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentInbox_ListDocuments_FullMethodName    = "/logiflow.documents.v1.DocumentInbox/ListDocuments"
	DocumentInbox_DownloadDocument_FullMethodName = "/logiflow.documents.v1.DocumentInbox/DownloadDocument"
)

// DocumentInboxClient is the client API for DocumentInbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentInboxClient interface {
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	DownloadDocument(ctx context.Context, in *DownloadDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentChunk], error)
}

type documentInboxClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentInboxClient(cc grpc.ClientConnInterface) DocumentInboxClient {
	return &documentInboxClient{cc}
}

func (c *documentInboxClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, DocumentInbox_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentInboxClient) DownloadDocument(ctx context.Context, in *DownloadDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentInbox_ServiceDesc.Streams[0], DocumentInbox_DownloadDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadDocumentRequest, DocumentChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentInbox_DownloadDocumentClient = grpc.ServerStreamingClient[DocumentChunk]

// DocumentInboxServer is the server API for DocumentInbox service.
// All implementations must embed UnimplementedDocumentInboxServer
// for forward compatibility.
type DocumentInboxServer interface {
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	DownloadDocument(*DownloadDocumentRequest, grpc.ServerStreamingServer[DocumentChunk]) error
	mustEmbedUnimplementedDocumentInboxServer()
}

// UnimplementedDocumentInboxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentInboxServer struct{}

func (UnimplementedDocumentInboxServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedDocumentInboxServer) DownloadDocument(*DownloadDocumentRequest, grpc.ServerStreamingServer[DocumentChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadDocument not implemented")
}
func (UnimplementedDocumentInboxServer) mustEmbedUnimplementedDocumentInboxServer() {}
func (UnimplementedDocumentInboxServer) testEmbeddedByValue()                       {}

// UnsafeDocumentInboxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentInboxServer will
// result in compilation errors.
type UnsafeDocumentInboxServer interface {
	mustEmbedUnimplementedDocumentInboxServer()
}

func RegisterDocumentInboxServer(s grpc.ServiceRegistrar, srv DocumentInboxServer) {
	// If the following call pancis, it indicates UnimplementedDocumentInboxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentInbox_ServiceDesc, srv)
}

func _DocumentInbox_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentInboxServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentInbox_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentInboxServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentInbox_DownloadDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentInboxServer).DownloadDocument(m, &grpc.GenericServerStream[DownloadDocumentRequest, DocumentChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentInbox_DownloadDocumentServer = grpc.ServerStreamingServer[DocumentChunk]

// DocumentInbox_ServiceDesc is the grpc.ServiceDesc for DocumentInbox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentInbox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logiflow.documents.v1.DocumentInbox",
	HandlerType: (*DocumentInboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDocuments",
			Handler:    _DocumentInbox_ListDocuments_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadDocument",
			Handler:       _DocumentInbox_DownloadDocument_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logiflow/documents/v1/documents.proto",
}
